name: run-app

on:
  schedule:
    - cron: '0 18 * * 1' # UTC 18:00 every Mondays
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    env:
      LUFA_CANCELER_CONFIG: ${{ secrets.LUFA_CANCELER_CONFIG }}
    steps:
      - 
        name: Build app
        run: |
          docker build -t canceler -f Dockerfile .
      - 
        name: Build app
        run: |
          docker run --rm -e LUFA_CANCELER_CONFIG canceler